on:
  push:
    branches: [ "main" ]

jobs:
  buildrepo:
    runs-on: ubuntu-latest

    steps:
      - uses: tidylabs/action-git-config-user@main
      - run: |
          git config user.name
          git config user.email
