on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "3.19.1" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    container:
      image: alpine:${{ needs.job1.outputs.output1 }}
    steps:
      - run: echo "$(cat /etc/alpine-release)"
