on:
  push:
    branches: [ "main" ]

jobs:
  buildrepo:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "whoami: $(whoami)"
          echo "HOME: $HOME"
          echo "/etc/passwd: \n$(cat /etc/passwd)"
