on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      alpine_version_minor: ${{ steps.step1.outputs.alpine_version_minor }}
    steps:
      - id: step1
        run: echo "alpine_version_minor=3.19.1" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    container:
      image: alpine:${{ needs.job1.outputs.alpine_version_minor }}
    steps:
      - run: echo "$(cat /etc/alpine-release)"
