on:
  push:
    branches: [ "main" ]

jobs:
  helloworld:
    runs-on: ubuntu-latest

    steps:
      - uses: tidylabs/action-git-config-user@main
      - run: |
          sudo apt-get install build-essential procps curl file git
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew info
        env:
          HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1


