on:
  push:
    branches: [ "main" ]

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: tidylabs/action-git-config-user@main
      - run: |
          echo "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew doctor
        env:
          HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1


