on:
  push:
    branches: [ "main" ]

jobs:
  buildrepo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/action-git-config-user
      - run: |
          git config user.name
          git config user.email
