on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  helloworld:
    runs-on: ubuntu-latest
    env:
      CASKS: >
        jck112/helloworld/balenaetcher
        jck112/helloworld/ffmpeg
      HOMEBREW_DEVELOPER: "1"
      HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: tidylabs/action-git-config-user@main
      - name: Setup homebrew
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          echo "$HOMEBREW_PREFIX/sbin" >> $GITHUB_PATH
          echo "$HOMEBREW_PREFIX/bin" >> $GITHUB_PATH

          echo "HOMEBREW_PREFIX=$HOMEBREW_PREFIX" >> $GITHUB_ENV
          echo "HOMEBREW_CELLAR=$HOMEBREW_CELLAR" >> $GITHUB_ENV
          echo "HOMEBREW_REPOSITORY=$HOMEBREW_REPOSITORY" >> $GITHUB_ENV
      - name: Setup tap
        run: |
          HOMEBREW_TAP_REPOSITORY=$(brew --repo $GITHUB_REPOSITORY)
          mkdir -vp "${HOMEBREW_TAP_REPOSITORY%/*}"
          ln -vs "$GITHUB_WORKSPACE" "$HOMEBREW_TAP_REPOSITORY"
      - name: Patch 'brew bump'
        run: |
          git -C "$HOMEBREW_REPOSITORY" apply \
          "$GITHUB_WORKSPACE/.github/workflows/brew-bump.patch"
      - name: Bump casks
        run: brew bump --open-pr --no-fork --automerge "$CASKS"


