on:
  push:
    branches: [ "main" ]

jobs:
  buildrepo:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "whoami: $(whoami)"
          printenv
          echo "/etc/passwd: \n$(cat /etc/passwd)"

      - uses: actions/checkout@v3

      - uses: ./.github/actions/alpine
